version: '2'

services:
  db:
    image: mysql:5.7
    container_name: dbmy     

    volumes:
      - ./db_files:/var/lib/mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: toor

    ports:
      - 3306:3306

  rails:
    image: rails:5.1.4
    container_name: drails     
    depends_on:
      - db
    build:
      context: ./
      dockerfile: DockerFileRails
    links:
      - db
    environment:
      DB_HOST: db:3306
      RAILS_ENV: development
   
    volumes:
      - ./app:/home/rails/app
      - ./bundle:/usr/local/bundle   

    ports:
      - 3000:3000
    tty: true  
