#!/bin/bash
# Bash wrappers for docker run commands
rake(){
	docker exec -it \
        --user $UID:$UID \
		drails \
		rake "$@"
}

rails(){
    docker exec -it \
        --user $UID:$UID \
        drails \
        rails "$@"
}

dbundle(){
    docker exec -it \
        --user $UID:$UID \
        drails \
        bundle "$@"
}

